#!/bin/bash


# ---- Config ----
choice=$1

# ---- Mission Starto -----
if ls $HOME/Pictures/Screenshots; then
  echo Detected
else
  mkdir -p $HOME/Pictures/Screenshots
fi
  

if [ $choice = screen ]; then
  grim $HOME/Pictures/Screenshots/$(date +'%a,%d[%H:%M:%S].png')
  if [ $? -eq 0 ]; then
    notify-send "Screenshot Captured!" -r 9005 -t 2000
  else 
    echo "error"
  fi
elif [ $choice = window ]; then
  activewindow1=$(hyprctl activewindow | grep at: | awk '{print $2}')
  activewindow2=$(hyprctl activewindow | grep size: | awk '{print $2}' | sed 's/,/x/')
  grim -g "$activewindow1 $activewindow2" $HOME/Pictures/Screenshots/Region-$(date +'%a,%d[%H:%M:%S].png')
  if [ $? -eq 0 ]; then
    notify-send "Window Region Captured!" -r 9005 -t 2000
  else 
    notify-send "There's no Active Window!" -r 9005 -t 2000
  fi
fi
    

