#!/bin/bash
choice=$1

if [ $choice = 1 ]; then
	waybar &
  	printf "" > $HOME/.bash/running
	notify-send Activated! -r 9001 -t 1000
  	while true; do
		running="$(cat $HOME/.bash/running)"
		id=$(ps -ef | grep '[w]aybar -c' | grep home | awk '{print $2}')
  		status="$(hyprctl activeworkspace | grep windows: | awk '{print $2}')"

		if [ "$status" -gt 0 ]; then
			if [ ! "$running" = 1 ]; then
				kill $id
        			printf 1 > $HOME/.bash/running
			fi
		fi
		
		if [ ! "$status" -gt 0 ]; then
			if [ ! "$running" = 0 ]; then
				kill $id
				printf 0 > $HOME/.bash/running
        			waybar -c $HOME/.config/waybar/home/config.jsonc -s $HOME/.config/waybar/home/style.css &
			fi
		fi
	done
else
  notify-send Killed -r 9001 -t 1000
	killall waybar &
	killall refresh &
	killall dunst &	
fi
